### ISSUE TITLE
Handle multiple quotes with same key.

### ISSUE THREAD

**Issue by RhinosF1** [RustyBower/sopel-quotes#4]
This is causing issues with our bots as they use the same database so sometimes both write the quote to the db if they're in both channels. We should handle the below exception:

[2020-08-06 23:31:25,240] sopel.bot ERROR - Unexpected error (Multiple rows were found for one_or_none()) from MacFan4000 at 2020-08-06 23:31:25.240731. Message was: .quote 3
Traceback (most recent call last):

File "/usr/local/lib/python3.7/dist-packages/sopel/bot.py", line 606, in call
  exit_code = func(sopel, trigger)
File "/usr/local/lib/python3.7/dist-packages/sopel_modules/quotes/quotes.py", line 183, in get_quote    quote = Quotes.search(argumentsList[0].strip(), bot)
File "/usr/local/lib/python3.7/dist-packages/sopel_modules/quotes/quotes.py", line 88, in search
  res = session.query(QuotesDB).filter(QuotesDB.key == key).filter(QuotesDB.active == 1).one_or_none()
File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/orm/query.py", line 3436, in one_or_none
  "Multiple rows were found for one_or_none()"
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()

**Comment by RustyBower** [comment]
This should be fixed with https://github.com/RustyBower/sopel-quotes/commit/f942842def2b5f7fc17f5bd91d13b9409989e284
